[build]
  command = "npm install && npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18.20.2"
  NPM_VERSION = "10.5.0"
  CI = false

[dev]
  command = "npm run dev"
  port = 4000
  targetPort = 4000
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
